// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!

@file:OptIn(kotlin.wasm.unsafe.UnsafeWasmMemoryApi::class, kotlin.wasm.ExperimentalWasmInterop::class, kotlin.wasm.unsafe.ComponentModelInternalApi::class)
@file:Suppress("REDUNDANT_ELSE_IN_WHEN")

package site.addzero.aio.plugin.kmpcomponent.bindings
import site.addzero.aio.plugin.kmpcomponent.component.PageRootFunctionsExportsImpl

import site.addzero.aio.plugin.kmpcomponent.bindings.runtime.*
import kotlin.wasm.unsafe.componentModelRealloc


@WitInterface("\$root")
internal /*external */interface PageRootFunctions {
  interface Exports{
    fun definition(): kotlin.String
    fun handle(request: kotlin.String): kotlin.String
  }

}
